# Generated by Django 2.2.6 on 2019-10-29 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_firstName', models.CharField(max_length=200)),
                ('owner_lastName', models.CharField(max_length=200)),
                ('owner_address', models.CharField(max_length=200)),
                ('owner_houseNumber', models.CharField(max_length=200)),
                ('owner_addressInfo', models.CharField(max_length=200)),
                ('owner_city', models.CharField(max_length=200)),
                ('owner_zipCode', models.CharField(max_length=200)),
                ('owner_phoneNumber', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=200)),
                ('pet_dateOfBirth', models.DateTimeField(verbose_name='date of birth')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petclinic.Owner')),
            ],
        ),
        migrations.CreateModel(
            name='PetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petType_text', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty_text', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_text', models.CharField(max_length=200)),
                ('visit_date', models.DateTimeField(verbose_name='date visited')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petclinic.Pet')),
            ],
        ),
        migrations.CreateModel(
            name='Veterinarian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veterinarian_firstName', models.CharField(max_length=200)),
                ('veterinarian_lastName', models.CharField(max_length=200)),
                ('specialties', models.ManyToManyField(to='petclinic.Specialty')),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='petType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petclinic.PetType'),
        ),
    ]
