# Generated by Django 2.2.6 on 2019-10-31 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petclinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='owner_address_info',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
