# Use postgres/example user/password credentials
version: '3.3'

services:

  db:
    image: postgres:11.5
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespwd
      POSTGRES_DB: django_petclinic
      CHARSET: UTF8
      PGPORT: 5432

  dbtest:
    image: postgres:11.5
    restart: always
    ports:
      - 5464:5464
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespwd
      POSTGRES_DB: django_petclinic_test
      CHARSET: UTF8
      PGPORT: 5464

  adminer:
    image: adminer:4.7.4
    restart: always
    ports:
      - 8080:8080
